server {
    listen 80;

    # Routes http://localhost/ to the dev server
    location / {
        proxy_pass http://instant-dev-server:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Routes http://localhost/matrix to the matrix dashboard
    location /matrix/ {
        proxy_pass http://matrix-dashboard:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}